import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { srtToVtt, validateSrt, validateVtt, vttToSrt } from "../src/index.js";

describe("srtToVtt", () => {
  it("converts SRT cues to WebVTT", () => {
    const input = `1
00:00:01,000 --> 00:00:03,500
Hello from StageCaptions.

2
00:00:04,000 --> 00:00:05,250
This is a second cue.`;

    const output = srtToVtt(input);

    assert.equal(
      output,
      `WEBVTT

00:00:01.000 --> 00:00:03.500
Hello from StageCaptions.

00:00:04.000 --> 00:00:05.250
This is a second cue.
`,
    );
  });

  it("preserves multiline cue text", () => {
    const input = `1
00:00:01,000 --> 00:00:04,000
First line
Second line`;

    const output = srtToVtt(input);

    assert.equal(
      output,
      `WEBVTT

00:00:01.000 --> 00:00:04.000
First line
Second line
`,
    );
  });

  it("can preserve SRT indexes as WebVTT cue identifiers", () => {
    const input = `42
00:00:01,000 --> 00:00:04,000
Named cue`;

    const output = srtToVtt(input, { preserveCueIds: true });

    assert.equal(
      output,
      `WEBVTT

42
00:00:01.000 --> 00:00:04.000
Named cue
`,
    );
  });

  it("normalizes BOM, CRLF, and short millisecond values", () => {
    const input = "\uFEFF1\r\n00:00:01,5 --> 00:00:04,25\r\nHello";

    const output = srtToVtt(input);

    assert.equal(
      output,
      `WEBVTT

00:00:01.500 --> 00:00:04.250
Hello
`,
    );
  });

  it("throws on malformed timestamp lines", () => {
    const input = `1
00:00:01 --> 00:00:02
Hello`;

    assert.throws(
      () => srtToVtt(input),
      /Invalid timestamp line\. Expected HH:MM:SS,mmm --> HH:MM:SS,mmm\. Line 2\./,
    );
  });
});

describe("validateSrt", () => {
  it("returns no warnings for valid SRT", () => {
    const input = `1
00:00:01,000 --> 00:00:02,000
Hello`;

    const warnings = validateSrt(input);

    assert.deepEqual(warnings, []);
  });

  it("warns on invalid timestamp lines", () => {
    const input = `1
00:00:01 --> 00:00:02
Hello`;

    const warnings = validateSrt(input);

    assert.deepEqual(warnings, [
      {
        code: "invalid-timestamp",
        line: 2,
        message: "Invalid timestamp line. Expected HH:MM:SS,mmm --> HH:MM:SS,mmm.",
      },
    ]);
  });

  it("warns when no cues are found", () => {
    const input = "This is not an SRT file.";

    const warnings = validateSrt(input);

    assert.deepEqual(warnings, [
      {
        code: "no-cues",
        line: 1,
        message: "No SRT cues found.",
      },
    ]);
  });
});

describe("vttToSrt", () => {
  it("converts WebVTT cues to SRT", () => {
    const input = `WEBVTT

00:00:01.000 --> 00:00:03.500
Hello from StageCaptions.

00:00:04.000 --> 00:00:05.250
This is a second cue.`;

    const output = vttToSrt(input);

    assert.equal(
      output,
      `1
00:00:01,000 --> 00:00:03,500
Hello from StageCaptions.

2
00:00:04,000 --> 00:00:05,250
This is a second cue.
`,
    );
  });

  it("preserves multiline cue text", () => {
    const input = `WEBVTT

00:00:01.000 --> 00:00:04.000
First line
Second line`;

    const output = vttToSrt(input);

    assert.equal(
      output,
      `1
00:00:01,000 --> 00:00:04,000
First line
Second line
`,
    );
  });

  it("can preserve WebVTT cue identifiers as SRT indexes", () => {
    const input = `WEBVTT

intro
00:00:01.000 --> 00:00:04.000
Named cue`;

    const output = vttToSrt(input, { preserveCueIds: true });

    assert.equal(
      output,
      `intro
00:00:01,000 --> 00:00:04,000
Named cue
`,
    );
  });

  it("skips WebVTT metadata blocks", () => {
    const input = `WEBVTT

NOTE generated by a video editor

STYLE
::cue { color: white; }

00:00:01.000 --> 00:00:04.000 align:start position:10%
Hello`;

    const output = vttToSrt(input);

    assert.equal(
      output,
      `1
00:00:01,000 --> 00:00:04,000
Hello
`,
    );
  });

  it("throws on malformed timestamp lines", () => {
    const input = `WEBVTT

00:00:01 --> 00:00:02
Hello`;

    assert.throws(
      () => vttToSrt(input),
      /Invalid timestamp line\. Expected HH:MM:SS\.mmm --> HH:MM:SS\.mmm\. Line 3\./,
    );
  });

  it("round trips SRT to VTT and back to SRT", () => {
    const input = `1
00:00:01,000 --> 00:00:03,500
Hello from StageCaptions.`;

    assert.equal(vttToSrt(srtToVtt(input)), `${input}\n`);
  });
});

describe("validateVtt", () => {
  it("returns no warnings for valid VTT", () => {
    const input = `WEBVTT

00:00:01.000 --> 00:00:02.000
Hello`;

    const warnings = validateVtt(input);

    assert.deepEqual(warnings, []);
  });

  it("warns on invalid timestamp lines", () => {
    const input = `WEBVTT

00:00:01 --> 00:00:02
Hello`;

    const warnings = validateVtt(input);

    assert.deepEqual(warnings, [
      {
        code: "invalid-timestamp",
        line: 3,
        message: "Invalid timestamp line. Expected HH:MM:SS.mmm --> HH:MM:SS.mmm.",
      },
    ]);
  });

  it("warns when no cues are found", () => {
    const input = "WEBVTT\n\nNOTE no cues here.";

    const warnings = validateVtt(input);

    assert.deepEqual(warnings, [
      {
        code: "no-cues",
        line: 1,
        message: "No VTT cues found.",
      },
    ]);
  });
});
